title: "Template"
description: "Template for new Jekyll Websites"
repository: enzanki-ars/template

header:
  left-header:
    - text: Home
      internal-link: index.html
    - text: Posts
      internal-link: posts.html

  right-header:
    - text: Privacy
      internal-link: privacy.html

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
